### ISSUE TITLE
Replace the image lightbox libraray

### ISSUE THREAD

**Issue by OriAmir** [OriAmir/React-Responsive-Gallery#15]

**Comment by choozn** [comment]
I support this as react-image-lightbox has serious performance problems on mobile due to this bug: https://github.com/frontend-collective/react-image-lightbox/issues/171 https://github.com/frontend-collective/react-image-lightbox/issues/187

**Comment by OriAmir** [comment]
Basically I'm working on my own light box library but it's will be very basic in the start, so not sure if I will merge it to here so fast..

Any idea about ready small bundle size and maintain library ? @choozn 

Thanks

**Comment by OriAmir** [comment]
done on version 3.0.3 with https://yet-another-react-lightbox.com/
in future want to create my own library but it's will take a while,
