### ISSUE TITLE
Enable Video Support

### ISSUE THREAD

**Issue by howdyhyber** [OriAmir/React-Responsive-Gallery#20]
Is it possible to add a video view support for this library?

**Comment by OriAmir** [comment]
hi @howdyhyber,
It's a good idea to add video support to the library, I may try to test adding that to the library in the near future. 
You are welcome also to create PR with that if it's interesting you.

Thanks!

**Comment by suntong** [comment]
Looking for the same thing; hope it'll be supported someday...

**Comment by suntong** [comment]
Online preview might be difficult, but show in list and offer to download might be an easier start, which will be more than good enough...

**Comment by OriAmir** [comment]
> Online preview might be difficult, but show in list and offer to download might be an easier start, which will be more than good enough...

Hi @suntong , can you pls explain more detailed your idea? You mean just adding symbol of video and download without video actually playing ?

**Comment by suntong** [comment]
Yeah, that will be more than good enough for me. 

Normally, for an event, or trip, we not only take pictures but short videos as well. I'm just hoping to find a ready-made package that can support both pictures and videos, together, not separately. The rest are all design details, bare-minimum is to be able to show it in the list and provide a way for people to download. If we need to provide a picture for the video ourselves, that's fine too. 

And further FYI, after that comment I did some further research and found that online viewing/preview seems to be not too difficult, based on this file

https://github.com/harryyizihan/around_web/blob/f882f4aeee4cd865db2f37272fed9de44057ae7b/src/components/Home.js#L112

and this Demo video: https://youtu.be/tXMTwyzDsZk

But this is only me judging from the surface...

Just hope that videos'll be supported someday, in any form or shape...

**Comment by OriAmir** [comment]
@suntong thanks, sounds like something I will try soon and update.
i open to PR as well!

**Comment by suntong** [comment]
Thanks. I'm not a JS/TS/front-end developer at all, :)

**Comment by OriAmir** [comment]
> Thanks. I'm not a JS/TS/front-end developer at all, :)

Ahah got it. 
Anyway if you could star ⭐️ the project it's will be great. Thanks and will update soon.

**Comment by OriAmir** [comment]
Done in v4

**Comment by suntong** [comment]
Bravo!!! 👏👏👏🎉🎉🎉
