### ISSUE TITLE
Types for lightBoxAdditionalProps too implicit

### ISSUE THREAD

**Issue by choozn** [OriAmir/React-Responsive-Gallery#25]
``Type is missing the following properties from type 'ILightBoxProps': mainSrc, onCloseRequestts(2739)``

Both mainSrc and onCloseRequestts should be optional in the interface so you are able to provide additional lightbox props.
The type interface should be 
```ts
interface AdditionalILightBoxProps extends Omit<ILightBoxProps, "mainSrc" | "onCloseRequest"> { 
    mainSrc?: string;
    onCloseRequest?(): void;
}
```

**Comment by OriAmir** [comment]
Hi @choozn thanks for let me know about that. I will take a look on that asap and update.

**Comment by OriAmir** [comment]
thanks @choozn , I added some other properties that were not relevant to this library and publish a release:
https://github.com/OriAmir/React-Responsive-Gallery/releases/tag/2.1.3
