### ISSUE TITLE
numOfImagesPerRow is not working as Expected

### ISSUE THREAD

**Issue by jsrockstaranks** [OriAmir/React-Responsive-Gallery#48]
Passing custom values in numOfImagesPerRow={{ xs: 1, s: 2, m: 3, l: 3, xl: 3, xxl: 3 }} still showing 5 images per rows.

Here is the screenshot of rendered page on my laptop, screen width 1440px.

<img width="1440" alt="Screenshot 2024-10-24 at 2 41 31 PM" src="https://github.com/user-attachments/assets/934da2c4-7ae3-4727-ac93-6c0820bc3dc9">

**Comment by jsrockstaranks** [comment]
I am expecting this to display 3 images per row for any device larger than tablet, for tablet or landscape mobile it should be 2 and for mobile portraits it is 1.

**Comment by jsrockstaranks** [comment]
Checked into the code and it is fixed by using numOfMediaPerRow instead of numOfImagesPerRow. Update the NPM page at https://www.npmjs.com/package/react-responsive-gallery/v/3.0.0-beta.2?activeTab=readme so another user won't create such issue.

**Comment by OriAmir** [comment]
Hello @jsrockstaranks  , yeah property name changed from v3 to v4. Thanks for the update.
