### ISSUE TITLE
REMOVE GALLEY ITEM

### ISSUE THREAD

**Issue by christianzegarra** [OriAmir/React-Responsive-Gallery#5]
Hello, I have a little problem.
When I send the image arrangement is there a way to remove the images from the gallery individually?

**Comment by OriAmir** [comment]
@CARDILAC  Hey, sorry for the delay in the response (Github just not notify me!)
Not understand you in 100%, you mean that you want to remove a specific image and to re-arrange your stuff?

please provide some code, then I Could help you!
