### ISSUE TITLE
Edit Lightbox caption and toolbar

### ISSUE THREAD

**Issue by sarahg813** [OriAmir/React-Responsive-Gallery#6]
Great work with this gallery!

Is there an option to edit the font-size for the lightbox caption (I want to make it bigger) and a way to add margin-top for the toolbar? The toolbar blocks the navbar of my site and when I click the X I end up clicking the navbar buttons.

![Screen Shot 2020-06-09 at 10 28 13 PM](https://user-images.githubusercontent.com/22378253/84220435-cda73c80-aaa0-11ea-8c39-5ff3094a86f2.png)

I hope you can help with this, thanks!

**Comment by OriAmir** [comment]
@sarahg813 Hey, sorry for the delay in the response (Github just not notify me!)
I pretty sure that there is some option for that in `React Image Lightbox`(https://www.npmjs.com/package/react-image-lightbox) library ( and then you could just pass that as a prop in `lightBoxAdditionalProps`)
Could you share your code? I could help you if you want.

**Comment by OriAmir** [comment]
@sarahg813 I close this issue since you it looks not relevant anymore.
If you have any questions pls open a new issue, tnx!
