### ISSUE TITLE
Failed to load local images from folder

### ISSUE THREAD

**Issue by AnushreeDhar** [OriAmir/React-Responsive-Gallery#8]
I intend to use local images and not src from url.. is that a bug or will be taken up later?

**Comment by OriAmir** [comment]
hi @AnushreeDhar .
I should implement and add that, you could also create a PR and send to me!

**Comment by AnushreeDhar** [comment]
Hi i

**Comment by AnushreeDhar** [comment]
sure let me know which branch to use thanks!

**Comment by OriAmir** [comment]
You could use the `develop` branch.
I think that we miss the `url-loader,` `file-loader` plugins in the webpack

thanks for your help !

**Comment by OriAmir** [comment]
@AnushreeDhar 
Hi, I check that,
I create a  simple `CRA`, add local images and it seems like it works.
```
      <ResponsiveGallery
        images={[
          {
            src: require("./img.png"),
          },
          {
            src:
              "https://cdn.pixabay.com/photo/2017/03/23/13/23/stag-2168278_960_720.jpg",
          },...]/>
```

You can see in the image below that it's local image:
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/17565646/92530557-49965980-f235-11ea-9c44-3dae04b3f68e.png">


If you are not using `CRA` and you use webpack to config your project pls add `file-loader` plugin to your webpack.config file:

```
  {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              esModule: false,
            },
          },
        ],
      }
```

if you have any other question I will glad to help you.

**Comment by AnushreeDhar** [comment]
okay mine require isnt working i tried with src: `${pic1}`, this worked! but thanks for your help

**Comment by OriAmir** [comment]
sure, if you have any other issue/suggestion pls contact me / open an issue,tnx!
