### ISSUE TITLE
Getting "Window is not defined" error on NextJS. Presumably there's no SSR support

### ISSUE THREAD

**Issue by davidgoldcode** [OriAmir/React-Responsive-Gallery#9]

**Comment by OriAmir** [comment]
hi @davidgoldcode 
You right, currently the library don't support SSR

If you want you could open an MR and I will love to support that.

**Comment by joebImagine** [comment]
I ran into this same problem in NextJs.  At least for now you will need to import this component like so: 

`const ResponsiveGallery = dynamic(
  () => import('react-responsive-gallery'),
  { ssr: false }
);`

from the docs: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

**Comment by OriAmir** [comment]
thanks @joebImagine  !
@davidgoldcode I close this issue since we have a solution , if you have any other issues please open another issue,tnx.

**Comment by PaulHaze** [comment]
> I ran into this same problem in NextJs. At least for now you will need to import this component like so:
> 
> `const ResponsiveGallery = dynamic( () => import('react-responsive-gallery'), { ssr: false } );`
> 
> from the docs: https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

Ran into this exact same issue and this solved it. Thanks :)
